In [5]:
import numpy as np

In [6]:
print(np.__version__)

1.12.1


In [7]:
np.show_config

<function numpy.__config__.show>

In [8]:
np.zeros(10)

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [11]:
Z = np.zeros((10,10))
print(Z.size)
print(Z.itemsize)
print("%d bytes" % (Z.size * Z.itemsize))

100
8
800 bytes


In [12]:
np.info(np.add)

add(x1, x2[, out])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.  If ``x1.shape != x2.shape``, they must be
    broadcastable to a common shape (which may be the shape of one or
    the other).

Returns
-------
add : ndarray or scalar
    The sum of `x1` and `x2`, element-wise.  Returns a scalar if
    both  `x1` and `x2` are scalars.

Notes
-----
Equivalent to `x1` + `x2` in terms of array broadcasting.

Examples
--------
>>> np.add(1.0, 4.0)
5.0
>>> x1 = np.arange(9.0).reshape((3, 3))
>>> x2 = np.arange(3.0)
>>> np.add(x1, x2)
array([[  0.,   2.,   4.],
       [  3.,   5.,   7.],
       [  6.,   8.,  10.]])


In [15]:
Z = np.zeros(10)
Z[4] = 1
print(Z)

[ 0.  0.  0.  0.  1.  0.  0.  0.  0.  0.]


In [17]:
Z = np.arange(10,50)
print(Z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34
 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [18]:
Z = Z[::-1]
print(Z)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26 25
 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [19]:
Z = np.arange(9).reshape(3,3)
print(Z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [20]:
nz = np.nonzero([1,2,0,0,4,0])
print(nz)

(array([0, 1, 4]),)


In [21]:
print(np.eye(3))

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


In [22]:
print(np.random.random((3,3,3)))

[[[ 0.5521258   0.29565422  0.64241231]
  [ 0.94587377  0.62545516  0.42539287]
  [ 0.79712185  0.77734074  0.6970941 ]]

 [[ 0.17289539  0.9482526   0.23454469]
  [ 0.82215451  0.67451468  0.79129672]
  [ 0.80218945  0.55584339  0.92198457]]

 [[ 0.27702701  0.68089989  0.17343461]
  [ 0.96796995  0.5235033   0.23919137]
  [ 0.66139912  0.39282685  0.22797042]]]


In [23]:
Z = np.random.random((10,10))
Zmin, Zmax = Z.min(), Z.max()
print(Zmin, Zmax)

0.00413014313566 0.992385956941


In [25]:
Z = np.random.random(30)
m = Z.mean()
print(m)

0.504661301274


In [26]:
Z = np.ones((10,10))
Z[1:-1,1:-1] = 0
print(Z)

[[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]]


In [28]:
Z = np.ones((5,5))
Z = np.pad(Z, pad_width=1, mode='constant', constant_values = 0)
print(Z)

[[ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  1.  1.  1.  1.  1.  0.]
 [ 0.  1.  1.  1.  1.  1.  0.]
 [ 0.  1.  1.  1.  1.  1.  0.]
 [ 0.  1.  1.  1.  1.  1.  0.]
 [ 0.  1.  1.  1.  1.  1.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]]


In [29]:
print(1 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(0.3 == 3 * 0.1)

nan
False
False
nan
False


In [32]:
Z = np.diag(1+np.arange(4),k=-1)
print(Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [33]:
np.arange(4)

array([0, 1, 2, 3])

In [41]:
Z = np.zeros((8,8), dtype=int)
print(Z)

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]


In [43]:
Z[1::2,::2] = 1
Z[::2, 1::2] =1
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [44]:
print(np.unravel_index(100,(6,7,8)))

(1, 5, 4)


In [46]:
Z = np.tile(np.array([[0,1],[1,0]]),(4,4))
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [47]:
Z = np.random.random((5,5))
Zmax, Zmin = Z.max(), Z.min()
Z = (Z - Zmin)/(Zmax - Zmin)
print(Z)

[[ 0.46643559  0.40411423  0.          0.64327274  0.73511521]
 [ 0.10895844  1.          0.69872046  0.49781075  0.87503746]
 [ 0.58974954  0.77158399  0.51069506  0.88914754  0.56626925]
 [ 0.0472043   0.45358191  0.99663219  0.53184716  0.06716762]
 [ 0.84346427  0.6750387   0.94686952  0.87538516  0.83945524]]


In [50]:
color = np.dtype([("r", np.ubyte, 1),
                  ("g", np.ubyte, 1),
                  ("b", np.ubyte, 1),
                  ("a", np.ubyte, 1)])

In [51]:
color

dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

In [52]:
Z = np.dot(np.ones((5,3)), np.ones((3,2)))
print(Z)

[[ 3.  3.]
 [ 3.  3.]
 [ 3.  3.]
 [ 3.  3.]
 [ 3.  3.]]


In [53]:
Z = np.arange(11)
Z[(3 < Z) & (Z <= 8)] *= -1
print(Z)

[ 0  1  2  3 -4 -5 -6 -7 -8  9 10]


In [54]:
print(sum(range(5),-1))

9


In [55]:
from numpy import *
print(sum(range(5),-1))

10


In [58]:
a = range(0,5)
a

range(0, 5)

In [60]:
Z = np.arange(5)
Z

array([0, 1, 2, 3, 4])

In [61]:
Z**Z

array([  1,   1,   4,  27, 256])

In [62]:
print(np.array(0) / np.array(0))

nan


/home/szu/anaconda3/lib/python3.6/site-packages/ipykernel/__main__.py:1: RuntimeWarning: invalid value encountered in true_divide
  if __name__ == '__main__':


In [63]:
np.array(0) // np.array(0)

/home/szu/anaconda3/lib/python3.6/site-packages/ipykernel/__main__.py:1: RuntimeWarning: divide by zero encountered in floor_divide
  if __name__ == '__main__':


0

In [64]:
np.array([np.nan]).astype(int).astype(float)

array([ -9.22337204e+18])

In [65]:
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
print(np.intersect1d(Z1,Z2))

[1 5 7 8 9]


In [67]:
Z = np.random.uniform(0,10,10)
Z

array([ 2.13523816,  8.21324283,  6.20899685,  3.70327609,  4.14701066,
        8.9493362 ,  8.75941184,  0.31373215,  3.00958387,  1.16492723])

In [69]:
print(np.floor(Z))
print(np.ceil(Z)-1)
print(Z.astype(int))
print(np.trunc(Z))

[ 2.  8.  6.  3.  4.  8.  8.  0.  3.  1.]
[ 2.  8.  6.  3.  4.  8.  8.  0.  3.  1.]
[2 8 6 3 4 8 8 0 3 1]
[ 2.  8.  6.  3.  4.  8.  8.  0.  3.  1.]


In [70]:
def generate():
    for x in range(10):
        yield x
Z = np.fromiter(generate(),dtype=float,count=-1)
print (Z)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9.]


In [71]:
print(np.arange(10))

[0 1 2 3 4 5 6 7 8 9]


In [72]:
Z = np.linspace(0,1,11,endpoint=False)[1:]
print (Z)

[ 0.09090909  0.18181818  0.27272727  0.36363636  0.45454545  0.54545455
  0.63636364  0.72727273  0.81818182  0.90909091]


In [73]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
# Assuming identical shape of the arrays and a tolerance for the comparison of values
equal = np.allclose(A,B)
print(equal)

True


In [74]:
Z = np.zeros(10)
Z.flags.writeable = False
Z[0] = 1

ValueError: assignment destination is read-only

In [75]:
Z = np.random.random(10)
Z[Z.argmax()] = 0
print (Z)

[ 0.5365487   0.6611356   0.          0.1423833   0.6428824   0.89279041
  0.95357402  0.76269218  0.24912176  0.20947707]


In [76]:
np.set_printoptions(threshold=np.nan)
Z = np.zeros((16,16))
print (Z)

[[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0. 

In [77]:
Z = np.zeros(10, [ ('position', [ ('x', float, 1),
                                  ('y', float, 1)]),
                   ('color',    [ ('r', float, 1),
                                  ('g', float, 1),
                                  ('b', float, 1)])])
print (Z)

[(( 0.,  0.), ( 0.,  0.,  0.)) (( 0.,  0.), ( 0.,  0.,  0.))
 (( 0.,  0.), ( 0.,  0.,  0.)) (( 0.,  0.), ( 0.,  0.,  0.))
 (( 0.,  0.), ( 0.,  0.,  0.)) (( 0.,  0.), ( 0.,  0.,  0.))
 (( 0.,  0.), ( 0.,  0.,  0.)) (( 0.,  0.), ( 0.,  0.,  0.))
 (( 0.,  0.), ( 0.,  0.,  0.)) (( 0.,  0.), ( 0.,  0.,  0.))]


In [78]:
Z = np.arange(10, dtype=np.int32)
Z = Z.astype(np.float32, copy=False)
print (Z)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9.]


In [79]:
Z = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(Z):
    print (index, value)
for index in np.ndindex(Z.shape):
    print (index, Z[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


In [80]:
X = np.random.rand(5, 10)
Y = X - X.mean(axis=1, keepdims=True)
print(Y)

[[ 0.12235532 -0.38573395 -0.43726549 -0.42101978 -0.11026078  0.27628301
   0.16983456  0.3821431   0.14436146  0.25930255]
 [-0.48458645 -0.51915094  0.27059848  0.20408703 -0.05049152  0.27637664
   0.20730309 -0.06365638 -0.22729456  0.38681461]
 [-0.4665074  -0.11623405  0.24215387 -0.12147276 -0.10342086  0.12608918
   0.06814389  0.29058399  0.37589793 -0.29523378]
 [-0.55057008  0.1181966   0.20348845  0.09389705  0.15328852 -0.41930389
   0.2296466  -0.33288627  0.21936518  0.28487784]
 [-0.1197068  -0.02161901 -0.3609677  -0.02585438  0.10323157  0.34531889
   0.06109735  0.19904898  0.35618947 -0.53673836]]


In [81]:
Z = np.random.randint(0,10,(3,3))
print (Z)
print (Z[Z[:,1].argsort()])

[[3 2 4]
 [7 0 9]
 [3 2 4]]
[[7 0 9]
 [3 2 4]
 [3 2 4]]


In [82]:
Z = np.random.randint(0,3,(3,10))
print ((~Z.any(axis=0)).any())

False


In [83]:
A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
it = np.nditer([A,B,None])
for x,y,z in it: 
    z[...] = x + y
print (it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


In [84]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'name', "no name")

Z = NamedArray(np.arange(10), "range_10")
print (Z.name)

range_10


In [85]:
A = np.arange(25).reshape(5,5)
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [86]:
A[[0,1]] = A[[1,0]]
print (A)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [87]:
A[[0,1]] 

array([[5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4]])

In [88]:
A[[1,0]]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [89]:
Z = np.random.randint(0,10,50)
print (np.bincount(Z).argmax())

2


In [90]:
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5

# Slow
print (Z[np.argsort(Z)[-n:]])

[9995 9996 9997 9998 9999]


In [91]:
Z = np.random.randint(0,5,(10,3))
print (Z)

# solution for arrays of all dtypes (including string arrays and record arrays)
E = np.all(Z[:,1:] == Z[:,:-1], axis=1)
U = Z[~E]
print (U)

[[2 1 1]
 [2 1 1]
 [1 0 4]
 [2 4 2]
 [0 3 3]
 [0 2 2]
 [1 2 3]
 [1 3 3]
 [2 2 2]
 [4 1 1]]
[[2 1 1]
 [2 1 1]
 [1 0 4]
 [2 4 2]
 [0 3 3]
 [0 2 2]
 [1 2 3]
 [1 3 3]
 [4 1 1]]


In [92]:
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128])
B = ((I.reshape(-1,1) & (2**np.arange(8))) != 0).astype(int)
print(B[:,::-1])

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


In [93]:
Z = np.random.randint(0,2,(6,3))
T = np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))
_, idx = np.unique(T, return_index=True)
uZ = Z[idx]
print (uZ)

[[0 1 0]
 [0 1 1]
 [1 0 0]
 [1 0 1]]
