In [1]:
import pandas as pd

In [2]:
from pandas import Series, DataFrame

In [3]:
obj = pd.Series([4,7,-5,3])

In [4]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [6]:
obj.values

array([ 4,  7, -5,  3])

In [7]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [8]:
obj2 = pd.Series([4,7,-5,3], index=['d', 'b', 'a', 'c'])

In [9]:
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [10]:
obj2.index

Index(['d', 'b', 'a', 'c'], dtype='object')

In [11]:
obj2['a']

-5

In [12]:
obj2[['a', 'c', 'd']]

a   -5
c    3
d    4
dtype: int64

In [13]:
obj2[obj2>0]

d    4
b    7
c    3
dtype: int64

In [14]:
obj2 * 2

d     8
b    14
a   -10
c     6
dtype: int64

In [16]:
import numpy as np

In [17]:
np.exp(obj2)

d      54.598150
b    1096.633158
a       0.006738
c      20.085537
dtype: float64

In [18]:
'b' in obj2

True

In [19]:
sdata = {'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}

In [20]:
obj3 = pd.Series(sdata)

In [21]:
obj3

Ohio      35000
Oregon    16000
Texas     71000
Utah       5000
dtype: int64

In [22]:
states = ['California', 'Ohio', 'Oregon', 'Texas']

In [23]:
obj4 = pd.Series(sdata, index=states)

In [24]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [25]:
pd.isnull(obj4)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [26]:
pd.notnull(obj4)

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [27]:
obj3 + obj4

California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64

In [28]:
obj4.name = 'population'

In [29]:
obj4.index.name = 'state'

In [30]:
obj4

state
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

In [31]:
data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada',
'Nevada'],
'year': [2000, 2001, 2002, 2001, 2002, 2003],
'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}

In [32]:
frame = pd.DataFrame(data)

In [33]:
frame

pop   state  year
0  1.5    Ohio  2000
1  1.7    Ohio  2001
2  3.6    Ohio  2002
3  2.4  Nevada  2001
4  2.9  Nevada  2002
5  3.2  Nevada  2003

In [35]:
frame.head()

pop   state  year
0  1.5    Ohio  2000
1  1.7    Ohio  2001
2  3.6    Ohio  2002
3  2.4  Nevada  2001
4  2.9  Nevada  2002

In [36]:
pd.DataFrame(data, columns=['year', 'state', 'pop'])

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2

In [37]:
frame2 = pd.DataFrame(data, columns=['year', 'state', 'pop',
'debt'],index=['one', 'two', 'three', 'four','five', 'six'])

In [38]:
frame2

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN
six    2003  Nevada  3.2  NaN

In [39]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [40]:
frame2['state']

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
six      Nevada
Name: state, dtype: object

In [41]:
frame2.loc['three']

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: three, dtype: object

In [42]:
frame2['debt'] = 16.5

In [43]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5  16.5
two    2001    Ohio  1.7  16.5
three  2002    Ohio  3.6  16.5
four   2001  Nevada  2.4  16.5
five   2002  Nevada  2.9  16.5
six    2003  Nevada  3.2  16.5

In [44]:
frame2['debt'] = np.arange(6.)

In [45]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   0.0
two    2001    Ohio  1.7   1.0
three  2002    Ohio  3.6   2.0
four   2001  Nevada  2.4   3.0
five   2002  Nevada  2.9   4.0
six    2003  Nevada  3.2   5.0

In [46]:
val = pd.Series([-1.2, -1.5, -1.7], index = ['two','four','six'])

In [47]:
frame2['debt'] = val

In [48]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9   NaN
six    2003  Nevada  3.2  -1.7

In [49]:
frame2['eastern'] = frame2.state == 'Ohio'

In [50]:
frame2

year   state  pop  debt eastern
one    2000    Ohio  1.5   NaN    True
two    2001    Ohio  1.7  -1.2    True
three  2002    Ohio  3.6   NaN    True
four   2001  Nevada  2.4  -1.5   False
five   2002  Nevada  2.9   NaN   False
six    2003  Nevada  3.2  -1.7   False

In [51]:
del frame2['eastern']

In [52]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [53]:
pop = {'Nevada': {2001: 2.4, 2002: 2.9}, 'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}}

In [54]:
frame3 = pd.DataFrame(pop)

In [55]:
frame3

Nevada  Ohio
2000     NaN   1.5
2001     2.4   1.7
2002     2.9   3.6

In [56]:
frame3.T

2000  2001  2002
Nevada   NaN   2.4   2.9
Ohio     1.5   1.7   3.6

In [57]:
pd.DataFrame(pop, index=[2001, 2002,2003])

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2003     NaN   NaN

In [58]:
pdata = {'Ohio': frame3['Ohio'][:-1], 'Nevada': frame3['Nevada'][:2]}

In [59]:
pd.DataFrame(pdata)

Nevada  Ohio
2000     NaN   1.5
2001     2.4   1.7

In [60]:
frame3.index.name = 'year'

In [61]:
frame3.columns.name = 'state'

In [62]:
frame3

state  Nevada  Ohio
year               
2000      NaN   1.5
2001      2.4   1.7
2002      2.9   3.6

In [63]:
frame3.values

array([[ nan,  1.5],
       [ 2.4,  1.7],
       [ 2.9,  3.6]])

In [64]:
frame2.values

array([[2000, 'Ohio', 1.5, nan],
       [2001, 'Ohio', 1.7, -1.2],
       [2002, 'Ohio', 3.6, nan],
       [2001, 'Nevada', 2.4, -1.5],
       [2002, 'Nevada', 2.9, nan],
       [2003, 'Nevada', 3.2, -1.7]], dtype=object)

In [65]:
obj = pd.Series(range(3), index=['a', 'b', 'c'])

In [66]:
index = obj.index

In [67]:
obj

a    0
b    1
c    2
dtype: int64

In [68]:
index

Index(['a', 'b', 'c'], dtype='object')

In [69]:
index[:-1]

Index(['a', 'b'], dtype='object')

In [73]:
index[:2]

Index(['a', 'b'], dtype='object')

In [74]:
index[1] = 'd'

TypeError: Index does not support mutable operations

In [75]:
labels = pd.Index(np.arange(3))

In [76]:
labels

Int64Index([0, 1, 2], dtype='int64')

In [79]:
obj2 = pd.Series([1.5, -2.5, 0], index=labels)

In [80]:
obj2

0    1.5
1   -2.5
2    0.0
dtype: float64

In [81]:
frame3

state  Nevada  Ohio
year               
2000      NaN   1.5
2001      2.4   1.7
2002      2.9   3.6

In [82]:
obj = pd.Series([4.5, 7.2, -5.3, 3.6], index=['d', 'b', 'a',
'c'])

In [83]:
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [84]:
obj2 = obj.reindex(['a', 'b', 'c', 'd', 'e'])

In [85]:
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [86]:
obj3 = pd.Series(['blue', 'purple', 'yellow'], index=[0, 2,
4])

In [87]:
obj3

0      blue
2    purple
4    yellow
dtype: object

In [88]:
obj3.reindex(range(6), method='ffill')

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [89]:
frame = pd.DataFrame(np.arange(9).reshape((3,3)), index=['a', 'c', 'd'], columns=['Ohio','Texas','California'])

In [90]:
frame

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [91]:
frame2 = frame.reindex(['a', 'b', 'c', 'd'])

In [92]:
frame2

Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [93]:
states = ['Texas', 'Utah', 'California']

In [94]:
frame2.reindex(columns=states)

Texas  Utah  California
a    1.0   NaN         2.0
b    NaN   NaN         NaN
c    4.0   NaN         5.0
d    7.0   NaN         8.0

In [95]:
obj = pd.Series(np.arange(5.), index=['a', 'b', 'c', 'd',
'e'])

In [96]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [98]:
new_obj = obj.drop('c')

In [99]:
new_obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [100]:
obj.drop(['d', 'c'])

a    0.0
b    1.0
e    4.0
dtype: float64

In [101]:
data = pd.DataFrame(np.arange(16).reshape((4,4)), index=['Ohio', 'Colorado', 'Utah', 'NewYork'], columns=['one', 'two', 'three',
'four'])

In [102]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
NewYork    12   13     14    15

In [103]:
data.drop(['Colorado', 'Ohio'])

one  two  three  four
Utah       8    9     10    11
NewYork   12   13     14    15

In [104]:
data.drop(['two', 'four'], axis='columns')

one  three
Ohio        0      2
Colorado    4      6
Utah        8     10
NewYork    12     14

In [105]:
obj = pd.Series(np.arange(4.), index=['a', 'b', 'c', 'd'])

In [106]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

In [107]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),index=['Ohio', 'Colorado', 'Utah', 'NewYork'],columns=['one', 'two', 'three',
'four'])

In [108]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
NewYork    12   13     14    15

In [109]:
data['two']

Ohio         1
Colorado     5
Utah         9
NewYork     13
Name: two, dtype: int64

In [110]:
data.loc['Colorado',['two','three']]

two      5
three    6
Name: Colorado, dtype: int64

In [111]:
ser = pd.Series(np.arange(3.))

In [112]:
ser

0    0.0
1    1.0
2    2.0
dtype: float64

In [114]:
ser.index[-1]

2

In [115]:
ser.loc[:1]

0    0.0
1    1.0
dtype: float64

In [116]:
ser.iloc[:1]

0    0.0
dtype: float64

In [119]:
s1 = pd.Series([7.3, -2.5, 3.4, 1.5], index=['a', 'c', 'd', 'e'])

In [120]:
s2 = pd.Series([-2.1, 3.6, -1.5, 4, 3.1],index=['a', 'c', 'e', 'f', 'g'])

In [121]:
s1+s2

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

In [122]:
frame = pd.DataFrame(np.arange(12.).reshape((4, 3)),columns=list('bde'),index=['Utah', 'Ohio', 'Texas','Oregon'])

In [123]:
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [124]:
series = frame.iloc[0]

In [125]:
series

b    0.0
d    1.0
e    2.0
Name: Utah, dtype: float64

In [126]:
frame - series

b    d    e
Utah    0.0  0.0  0.0
Ohio    3.0  3.0  3.0
Texas   6.0  6.0  6.0
Oregon  9.0  9.0  9.0

In [127]:
frame = pd.DataFrame(np.random.randn(4, 3),columns=list('bde'),index=['Utah', 'Ohio', 'Texas','Oregon'])

In [128]:
frame

b         d         e
Utah    0.182467  1.966634  1.541182
Ohio    1.697643 -0.454093 -1.997136
Texas  -1.336276 -1.073370  0.038159
Oregon -2.220806  0.104348  1.568280

In [129]:
f = lambda x: x.max() - x.min()

In [130]:
frame.apply(f)

b    3.918449
d    3.040004
e    3.565416
dtype: float64

In [131]:
frame.apply(f, axis='columns')

Utah      1.784167
Ohio      3.694779
Texas     1.374435
Oregon    3.789086
dtype: float64

In [132]:
obj = pd.Series(range(5), index=['a', 'a', 'b', 'b', 'c'])

In [133]:
obj.index.is_unique

False

In [134]:
df = pd.DataFrame([[1.4, np.nan], [7.1, -4.5],
.....:
[np.nan, np.nan], [0.75, -1.3]],
.....:
index=['a', 'b', 'c', 'd'],
.....:
columns=['one', 'two'])

In [135]:
df

one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

In [136]:
df.sum()

one    9.25
two   -5.80
dtype: float64

In [137]:
obj = pd.Series(['c', 'a', 'd', 'a', 'a', 'b', 'b', 'c',
'c'])

In [138]:
uniques = obj.unique()

In [139]:
uniques

array(['c', 'a', 'd', 'b'], dtype=object)